### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'Conekta.token.create')

### ISSUE THREAD

**Issue by memovillalobos** [conekta/conekta.js#15]
En la página con el ejemplo para tokenizar tarjetas, la línea 

```
Conekta.token.create($form, conektaSuccessResponseHandler, conektaErrorResponseHandler);
```

debería ser 

```
Conekta.Token.create($form, conektaSuccessResponseHandler, conektaErrorResponseHandler);
```

con T mayúscula...

**Comment by Janee** [comment]
Hola @memovillalobos 
¡Gracias por la información! Lo cambiaremos en unos instantes.

Bonito día.

**Comment by franciscobautista** [comment]
Todavía no han corregido su documentación.

**Comment by mauroarcet** [comment]
Conekta.token.create aún funciona https://github.com/conekta/conekta.js/blob/81b5cdb4ee6954ca5ea03184a7b83817459f6f00/src/token.js.coffee#L52

En unos momentos se verá reflejada la modificación en la documentación.
