### ISSUE TITLE
The `conekta_no_dependencies.js` script depends on jQuery

### ISSUE THREAD

**Issue by xiam** [conekta/conekta.js#19]
We're trying to use the non-dependencies version of Conekta's JavaScript API, but it seems that in order to work it actually requires jQuery.

You have this placeholder `conektaAjax` function here https://github.com/conekta/conekta.js/blob/master/dist/conekta_no_dependencies.js#L26, but since we're not using jQuery that `window.conektaAjax` variable will be undefined, the code does not provide an alternative for that and this is also not mentioned anywhere on the docs. Users are left alone to figure out that they need to define this `window.conektaAjax` function which creates initial confusion.

It would be nice to have a default Ajax function bundled within `conekta_no_dependencies.js`, otherwise that `no_dependencies` bit is misleading.

**Comment by Janee** [comment]
@xiam ¿puedes probar con conekta.js? Dicho archivo ya no necesita jQuery :)
