### ISSUE TITLE
Problem while running conekta.js within a cordova app

### ISSUE THREAD

**Issue by zardilior** [conekta/conekta.js#2]
I was running conekta.js with my  cordova app using the same code as in my webapp and it sends a request to the unexistent https://api.conekta.io/tokens/create/create.js while creating the token. In web it sends it to https://api.conekta.io/tokens which is correct and works. If I can't use conekta.js to sell physical products in my apps I will have to implement a different companie's services

**Comment by cristinarandall** [comment]
Hi there, thanks for reaching out about this issue. We are in the process of releasing a change to conekta.js to avoid this problem. In the meantime, could you please send us an email to contact@conekta.io ? That way we can provide you with a different version of conekta.js to use.
