### ISSUE TITLE
Angular 4 angular clie

### ISSUE THREAD

**Issue by cesarcastmore** [conekta/conekta.js#38]
Buenas noches

Estoy tratando de usar conekta para generar el token pero estoy teniendo problemas porque estoy usando como front-end angular 4 usando como framework angular clie que utiliza mucho webpack. ¿Tienes algun referencia sobre angular 4, como se debe de importar el modulo de conekta.js?

**Comment by eduardoconekta** [comment]
Has tratado de guiarte con el tutorial que tenemos para tarjeta ?, si buen no es angular 4 aquí tenemos los pasos de tokenización. Una pregunta como maneja angular 4 las dependencias ? 
hay problema en poner 
```
<script type="text/javascript" src="https://cdn.conekta.io/js/latest/conekta.js"></script>
```
dentro de tu template ? 
https://developers.conekta.com/tutorials/card?language=node

**Comment by VCGDEV** [comment]
@cesarcastmore 
Estoy usando Ionic 2 para una aplicación movil y también usando angular lo que hago es poner en el index
`<script type="text/javascript" src="https://cdn.conekta.io/js/latest/conekta.js"></script>`

y en mi componente 

`declare var Conekta:any;`

para tokenizar la tarjeta estoy utilizando esto:

`
   Conekta.setPublishableKey(this.envVariables.CONEKTA_KEY);
      Conekta.token.create({card:{
        number:this.form.get('cardNumber').value,
        name:this.form.get('name').value,
        exp_year:this.form.get('year').value,
        exp_month:this.form.get('month').value,
        cvc:this.form.get('cvc').value
      }},(token)=>{
        console.debug("Token : ",token);
        //usar el token
      },(error)=>{
        console.error(error);
        //mostrar mensaje de error al usuario
      })`

Saludos

**Comment by jito1989** [comment]
Saludos Amigo @VCGDEV  como tienes el código yo estoy tratando de implementar Conekta en ionic, tengo el llamado del js y tengo declarado la variable Conekta pero al ejecutar la función me marca ese error ERROR TypeError: Cannot read property 'setPublishableKey' of undefined

Espero y me puedas ayudar

**Comment by eduardoconekta** [comment]
@jito1989  en la función 
**setPublishableKey(this.envVariables.CONEKTA_KEY)**
**this.envVariables.CONEKTA_KEY** => es su llave de conekta solo que el la saca de sus variables de entorno, puedes ponerla de esa forma o pasando el String 
```
setPublishableKey('key_...')
```

**Comment by VCGDEV** [comment]
@jito1989 Claro mira, esto es lo que tengo en el index dentro del folder
/src/index.html

`<script type="text/javascript" src="https://cdn.conekta.io/js/latest/conekta.js"></script>`

Despues en el componente donde utilizare la tokenización de tarjetas tengo lo siguiente, despues de todos los imports que hagas

`declare var Conekta:any;`

y mi método que realiza la tokenizacion es así 

```
Conekta.setPublishableKey(this.envVariables.CONEKTA_KEY);
Conekta.token.create(
   {
      card:{
                number:this.form.get('cardNumber').value,
                name:this.form.get('name').value,
                exp_year:this.form.get('year').value,
                exp_month:this.form.get('month').value,
                cvc:this.form.get('cvc').value
      }
   },(token)=>{
          console.debug("Token : ",token);
          //aquí es donde mandas a llamar tu servicio para guardar el token o crear la orden
  },(error)=>{
//en esta parte le muestras el error al usuario, en dado caso que no se pueda tokenizar la tarjeta
//antes de enviar a tokenizar lo que yo hago es pasarlo por un validador para que llos datos a enviar sean correctos
  let msg = error.message_to_purchaser;
this.toastCtrl.create({dismissOnPageChange:true,position:'bottom',duration:4000,message:this.msg}).present();
  }
);
```

y esta es la información de ionic que tengo instalado

```
cli packages: (/home/dev06/.nvm/versions/node/v6.7.0/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.3.1
    Ionic Framework    : ionic-angular 3.1.1

System:

    Android SDK Tools : 26.0.2
    Node              : v6.7.0
    npm               : 4.6.1 
    OS                : Linux 3.13

Misc:

    backend : pro

```

**Comment by cesarcastmore** [comment]
@VCGDEV 
Estoy utilizando webpack, no tengo mucha experiencia en ionic

**Comment by VCGDEV** [comment]
@cesarcastmore yo también lo utilizo, y me genera el bundle sin problemas, lo que debes hacer es insertar el script como en cualquier otra pagina, tienes el proyecto en git? para darle una revisada y decirte donde insertar la url?

**Comment by cesarcastmore** [comment]
@VCGDEV  estuve revisando ionic y me encanto, me voy a cambiar a ese framework y aqui me funciono muy bien,
